#!/bin/bash
# Build Bloom & Burgle into a single .rbxlx via Rojo.
# Pre-build CI gate: enforce material discipline per design spec §1.5.
set -e

export PATH="$HOME/.rokit/bin:$PATH"
cd "$(dirname "$0")/.."

OUT="BloomAndBurgle.rbxlx"

# ── Material discipline (spec §1.5): SmoothPlastic, Plastic, Glass, Foil,
# and ForceField all read as "starter Roblox kit" against the steampunk
# identity. Any new occurrence in src/ fails the build.
echo "🔍 Material discipline check..."
# ERE pattern — must use unescaped parens with -E.
BANNED='Material\.(SmoothPlastic|Plastic|Glass|Foil|ForceField)\b'
HITS=$(grep -rn -E "$BANNED" src --include="*.luau" || true)
if [ -n "$HITS" ]; then
    echo "❌ Banned material(s) found in src/ — see Bloom&Burgle_Design_Spec.md §1.5"
    echo "$HITS"
    echo ""
    echo "   Approved alternatives: Metal, CorrodedMetal, Marble, Brick, Cobblestone,"
    echo "                          Wood, WoodPlanks, Slate, Concrete, Neon."
    exit 2
fi
echo "✅ Material discipline OK (no banned materials)"

# ── Telemetry config injection (Phase 0 / ADR-3).
# Generates TelemetryConfig.luau from BB_TELEMETRY_* env vars (set by .env
# during publish). File is gitignored — never committed. Empty values
# produce an empty-string stub which TelemetryBoot detects and falls back
# from cleanly (Studio Play / dev workflow stays unchanged).
TELEMETRY_CONFIG="src/ServerScriptService/TelemetryConfig.luau"
cat > "$TELEMETRY_CONFIG" <<TELEMETRY_EOF
--!strict
-- AUTO-GENERATED by scripts/build.sh from .env at build time.
-- Gitignored — never edit by hand. Re-runs on every build.
return {
	endpoint = "${BB_TELEMETRY_ENDPOINT:-}",
	ingestKey = "${BB_TELEMETRY_KEY:-}",
}
TELEMETRY_EOF
if [ -n "${BB_TELEMETRY_ENDPOINT:-}" ]; then
    echo "📡 Telemetry config injected (endpoint: ${BB_TELEMETRY_ENDPOINT})"
else
    echo "📡 Telemetry config: empty stub (no BB_TELEMETRY_ENDPOINT in env)"
fi

# ── Gamepass config injection (BAB-DESIGN-CRITIQUE Tier 2, 2026-05-10).
# Bakes the Tinkerer's Pass gamepass ID into the place at build time so
# the user doesn't have to edit Luau source for each republish. Same
# gitignored-config pattern as TelemetryConfig.
GAMEPASS_CONFIG="src/ServerScriptService/GamepassConfig.luau"
cat > "$GAMEPASS_CONFIG" <<GAMEPASS_EOF
--!strict
-- AUTO-GENERATED by scripts/build.sh from .env at build time.
-- Gitignored — never edit by hand. Re-runs on every build.
return {
	TinkererPassId = tonumber("${BB_TINKERER_PASS_ID:-0}") or 0,
}
GAMEPASS_EOF
if [ -n "${BB_TINKERER_PASS_ID:-}" ] && [ "${BB_TINKERER_PASS_ID}" != "0" ]; then
    echo "🎩 Gamepass config injected (Tinkerer's Pass ID: ${BB_TINKERER_PASS_ID})"
else
    echo "🎩 Gamepass config: empty stub (no BB_TINKERER_PASS_ID in env) — daily-reward 2× disabled until set"
fi

echo "🔨 Building Bloom & Burgle..."
rojo build -o "$OUT" default.project.json

if [ -f "$OUT" ]; then
    SIZE=$(du -h "$OUT" | cut -f1)
    echo "✅ Build complete: $SIZE"
else
    echo "❌ Build failed"
    exit 1
fi
